const header=document.querySelector('.site-header');const menuBtn=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>30));menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');document.body.classList.toggle('menu-open',open);menuBtn.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');menuBtn.setAttribute('aria-expanded','false')}));

const $=id=>document.getElementById(id);const form=$('bookingForm');const service=$('service');const tripType=$('tripType');const route=$('route');const vehicle=$('vehicle');const hours=$('hours');const total=$('quoteTotal');const errorBox=$('formError');
const routes={mia_miami_beach:110,mia_brickell:100,mia_fll:130,mia_boca:180,mia_west_palm:240,port_mia:100};const vehicleData={sedan:{adjust:-15,hourly:85},suv:{adjust:0,hourly:100},sprinter:{adjust:40,hourly:140},executive_sprinter:{adjust:80,hourly:180}};
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)}
function updateFields(){const hourly=service.value==='hourly';$('routeWrap').hidden=hourly;$('tripTypeWrap').hidden=hourly;$('hoursWrap').hidden=!hourly;document.querySelectorAll('.return-field').forEach(el=>el.hidden=hourly||tripType.value!=='round_trip');route.required=!hourly;hours.required=hourly;$('returnDate').required=!hourly&&tripType.value==='round_trip';$('returnTime').required=!hourly&&tripType.value==='round_trip';updateQuote()}
function updateQuote(){let amount;if(service.value==='hourly'){const h=Number(hours.value);amount=(vehicleData[vehicle.value]?.hourly||0)*h;if(h<3){total.textContent='3-hour minimum';return}}else{if(!route.value){total.textContent='Select a route';return}amount=(routes[route.value]+vehicleData[vehicle.value].adjust)*(tripType.value==='round_trip'?2:1)}total.textContent=money(amount)}
[service,tripType,route,vehicle,hours].forEach(el=>el.addEventListener('change',updateFields));hours.addEventListener('input',updateQuote);
const dateInput=$('date');const returnDate=$('returnDate');const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());const minDate=today.toISOString().split('T')[0];dateInput.min=minDate;returnDate.min=minDate;dateInput.addEventListener('change',()=>{returnDate.min=dateInput.value||minDate});updateFields();

form.addEventListener('submit',async e=>{e.preventDefault();errorBox.textContent='';const button=form.querySelector('.pay-button');button.disabled=true;button.textContent='Opening secure checkout…';const data={service:service.value,tripType:tripType.value,route:route.value,pickup:$('pickup').value,dropoff:$('dropoff').value,date:dateInput.value,time:$('time').value,returnDate:returnDate.value,returnTime:$('returnTime').value,hours:hours.value,vehicle:vehicle.value,passengers:$('passengers').value,luggage:$('luggage').value,flightNumber:$('flightNumber').value,airline:$('airline').value,pickupStyle:$('pickupStyle').value,childSeats:$('childSeats').value,fbo:$('fbo').value,name:$('name').value,email:$('email').value,phone:$('phone').value,specialRequests:$('specialRequests').value};try{const response=await fetch('/api/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to start payment.');location.href=result.url}catch(err){errorBox.textContent=err.message;button.disabled=false;button.textContent='Pay & Confirm Reservation'}});
